### ISSUE TITLE
詞庫補充

### ISSUE THREAD

**Issue by bluelovers** [ayaka14732/FanWunMing#1]
https://github.com/bluelovers/ws-segment/tree/master/packages/segment-dict/dict/synonym

**Comment by ayaka14732** [comment]
Unfortunately, as said in [《正確實現簡轉繁字型》 (_Correctly Implement a Simplified-Chinese-To-Traditional-Chinese Font_)](https://ayaka.shn.hk/s2tfont/hant/), an OpenType font can only possess a maximum of 65,535 glyphs. Therefore, I believe the dictionary could not be enlarged at this time.

**Comment by ayaka14732** [comment]
Hi, @bluelovers, I have removed many rare Chinese characters from the original font. There is enough space now. Would you please explain the usage of the files you provided?

**Comment by UltimateAmitieKaiNiC** [comment]
着字怎麼沒換成著呢？

**Comment by ayaka14732** [comment]
@UltimateAmitieKaiNiC 

`FanWunMing` 因為採用 OpenCC 用字，所以區分「着」、「著」；而 `FanWunMing-TW` 確實應該轉換為「著」。

可以再開一個 issue，下一個版本修復。
