### ISSUE TITLE
未能轉義

### ISSUE THREAD

**Issue by Singsonxd** [ayaka14732/FanWunMing#12]
![E8E579F6-6815-4961-96D1-32DA68B4A2CD](https://user-images.githubusercontent.com/7780188/112723491-c1b23b80-8f49-11eb-8c15-11c90ebe8fb8.png)
紅色背景的任務仍處於簡體

**Comment by ayaka14732** [comment]
應該是瀏覽器的 bug。在 Firefox 上是正常的：

![](https://user-images.githubusercontent.com/68557794/113122751-81eb9c80-9246-11eb-9055-6ebab5e9ec69.png)

**Comment by ayaka14732** [comment]
經過詢問羣友，這一問題與 #13 是相同問題，且在 OpenType 的框架下無解，所以關閉這個 issue，轉到 #13 繼續討論～
