### ISSUE TITLE
引號標點符號的全形半形問題

### ISSUE THREAD

**Issue by carecynthia** [ayaka14732/FanWunMing#19]
雖然簡中的“引號”有成功變成繁中的｢引號｣，但並非一般慣用的「全形」而是｢半形｣的，看起來排版會對不齊實在有點彆扭

**Comment by ayaka14732** [comment]
是的，這個是 upstream 的一個 bug。我一般是用 `font-feature-settings: "ss01" 1;` 指定全形變體
