### ISSUE TITLE
Is it possible to add some mathematical symbols such as degree ° ?

### ISSUE THREAD

**Issue by T-rvw** [ayaka14732/FanWunMing#21]
Hi, I am using this font file in an [open source 3D game engine](https://github.com/CatDogEngine/CatDogEngine) project. It works well in the Chinese & English environment but lacks of some mathematical symbols such as degree °.

**Comment by ayaka14732** [comment]
This should be fixed by 72db43b63232893239d8d92b898b208409ae4b0d and the font can be downloaded from [`FanWunMing.zip`](https://github.com/ayaka14732/FanWunMing/suites/14241225506/artifacts/799703458). However, I don't have time to test it. Feel free to reopen if it is not fixed.

**Comment by T-rvw** [comment]
> This should be fixed by [72db43b](https://github.com/ayaka14732/FanWunMing/commit/72db43b63232893239d8d92b898b208409ae4b0d) and the font can be downloaded from [`FanWunMing.zip`](https://github.com/ayaka14732/FanWunMing/suites/14241225506/artifacts/799703458). However, I don't have time to test it. Feel free to reopen if it is not fixed.

It works in my [test](https://github.com/CatDogEngine/CatDogEngine/pull/278). Thanks!
