### ISSUE TITLE
關於字體的小bug

### ISSUE THREAD

**Issue by aere21** [ayaka14732/FanWunMing#3]
在使用這字體之後**誒**字依然顯示成簡體**诶**

**Comment by ayaka14732** [comment]
感謝反饋。經檢查發現，這是由於本字體目前收字範圍為《通用規範漢字表》，而該表中沒有「诶」字，因此字體也沒有「诶」字，在顯示時回退到其他字體。我計劃在下一個版本中多收錄一些該表中沒有的字，就可以解決這一問題。

**Comment by aere21** [comment]
首先感謝開發者回覆,之後反映一下字體問題；瑸字好像也是缺字（應該和之前的誒字同一個問題）,使用字體後就直接顯示系統字體
如圖
![IMG_20201012_010821.jpg](https://user-images.githubusercontent.com/58069564/95684958-77513280-0c27-11eb-833a-7a44ee21865a.jpg)

**Comment by aere21** [comment]
還有一個問題就是當我在閱讀軟件上調較字距的時候,發現字距一旦有變動,就會造成簡變繁的效果失敗
如圖![Screenshot_2020-10-12-01-14-34-985_cn.deepink.reader.jpg](https://user-images.githubusercontent.com/58069564/95685139-9c927080-0c28-11eb-9ceb-200cfcb2accd.jpg)
（未修改字距）
![Screenshot_2020-10-12-01-14-39-575_cn.deepink.reader.jpg](https://user-images.githubusercontent.com/58069564/95685154-b0d66d80-0c28-11eb-83a9-38dfea5cb52a.jpg)
（修改字距後）
請問作者到底是字體的問題還是個別閱讀軟件的問題？😅
在最後感謝開發者為我們帶來更加精準的簡轉繁字體,作者辛苦了！

**Comment by ayaka14732** [comment]
關於字距的問題，我不能確定原因，可以再開一個 issue，待發現原因後再處理

**Comment by lxgw** [comment]
> 感謝反饋。經檢查發現，這是由於本字體目前收字範圍為《通用規範漢字表》，而該表中沒有「诶」字，因此字體也沒有「诶」字，在顯示時回退到其他字體。我計劃在下一個版本中多收錄一些該表中沒有的字，就可以解決這一問題。

可以添加 GB 2312 範圍內的字，在內地 GB 2312 比較常用。「诶」字在 GB 2312 範圍內，但在《通用規範漢字表》裏沒收錄，收錄的是「欸」。

**Comment by Jiali-Xing** [comment]
> 感謝反饋。經檢查發現，這是由於本字體目前收字範圍為《通用規範漢字表》，而該表中沒有「诶」字，因此字體也沒有「诶」字，在顯示時回退到其他字體。我計劃在下一個版本中多收錄一些該表中沒有的字，就可以解決這一問題。

嗨，謝謝開發這款獨一無二的簡轉繁字體！請問收字範圍現在已否有所調整？
我的問題是：好像很多字（比如粵字`攞冚喺冇哋啲嘢啱佢嘅咁屌咗噉㗎`）都缺字，請問是因爲《通用規範漢字表》的原因嗎？我在手機上使用該款字體，導致很多字fallback到黑體。請問有什麼解決辦法或建議嗎？

**Comment by ayaka14732** [comment]
確實是《通用規範漢字表》的原因。

目前還沒有找到更好的補充缺字的方法，現在的方法是手動添加到這裏：<https://github.com/ayaka14732/FanWunMing/blob/main/build/code_points_han.py#L29>

---

(20210908 更新)

現在是手動添加到這裏：<https://github.com/ayaka14732/opencc-font-generator/blob/main/setup.py#L172>

**Comment by Jiali-Xing** [comment]
哦，謝謝。看起來並不難，我可以抽空把我遇到的缺少的粵字（主要是上面列出的那些）加到那一行程式碼中去。
不過，妳希望我把修改後的code push回來嗎。（好像必須這樣做，因爲我沒有Mac無法獨立build這個字體 😢 ）
