### ISSUE TITLE
常用字字形表的問題

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [ayaka14732/FanWunMing#7]
在FanWunMing-TW怎麼還存在「着」字呢？
不過在字符怎麼沒有「裏」？

**Comment by NightFurySL2001** [comment]
https://github.com/ayaka14732/FanWunMing/issues/1
> I have removed many rare Chinese characters from the original font. 

恐怕已经将多数旧字形汉字移除了。我也发现“僞“字被移除了。

因此，伪字图的字符量已经开始影响日常使用。

与他人聊天时有人建议将伪字图替换为简单替换，毕竟部分替换方法可以使用简单替换 (GSUB) 达到同样效果。这样可以减少大量伪字符让更多汉字／词汇加入字体。
https://github.com/ayaka14732/FanWunMing/issues/2
